test_that("can install local package with dependencies then load and call functions from that package", {
  current_dir <- getwd()
  print(current_dir)
  dir <- tempdir()
  print(dir)
  setwd(dir)
  renv::init(force = T, bare = T)
  rvendor_path <- gsub(perl = T, "(?<=rvendor).*", "", current_dir)
  renv::install(rvendor_path, prompt = F)
  print("Initialized")
  source("renv/activate.R")
  package_dir <- paste0(current_dir, "/mockWithDeps")
  rvendor::install(package_dir, prompt = F)
  rvendor::activate()
  library(mockWithDeps)
  res <- hello_world()
  renv::deactivate()
  expect_equal(res, "hello")
})

